/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElRow: typeof import("element-plus/es")["ElRow"]
    IEpEdit: typeof import("~icons/ep/edit")["default"]
    IEpLoading: typeof import("~icons/ep/loading")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
  }
}
